In [82]:
import pandas
import numpy as np
price_df = pandas.read_csv("dataset/Price_table.csv")
sales_df = pandas.read_csv("dataset/Sales_table.csv")
trim_df = pandas.read_csv("dataset/Trim_table.csv")

In [83]:
# VOLVO Sales from 2016 - 2020
# X = sales_df[['Maker', "2016", "2017", "2018", "2019", "2020"]].values
volvo_sales = sales_df.loc[sales_df['Maker'] ==
                           'VOLVO', ["2016", "2017", "2018", "2019", "2020"]]
# sales by car ID
# volvo_sales_array = volvo_sales.values

# total sales (each year)
volvo_sales_sum = volvo_sales.sum(axis=0)

# return an array (each year)
volvo_sales_sum = volvo_sales.sum(axis=0).values

volvo_sales_sum

array([42914, 42273, 47659, 53773, 44328])

In [84]:
# Ferrari Sales from 2016 - 2020
X = sales_df[['Maker', "2016", "2017", "2018", "2019", "2020"]].values
ferrari_sales = sales_df.loc[sales_df['Maker'] ==
                             'FERRARI', ["2016", "2017", "2018", "2019", "2020"]]
# sales by car ID
# volvo_sales_array = volvo_sales.values

# total sales (each year)
ferrari_sales_sum = ferrari_sales.sum(axis=0)

# return an array (each year)
ferrari_sales_sum = ferrari_sales.sum(axis=0).values

np.array(ferrari_sales_sum)

array([472, 485, 488, 550, 468])

In [85]:
# Toyota Sales from 2016 - 2020
X = sales_df[['Maker', "2016", "2017", "2018", "2019", "2020"]].values
toyota_sales = sales_df.loc[sales_df['Maker'] ==
                            'TOYOTA', ["2016", "2017", "2018", "2019", "2020"]]
# sales by car ID
# volvo_sales_array = volvo_sales.values

# total sales (each year)
toyota_sales_sum = toyota_sales.sum(axis=0)

# return an array (each year)
toyota_sales_sum = toyota_sales.sum(axis=0).values

toyota_sales_sum

array([89822, 91954, 95267, 99904, 90020])

In [86]:
import pandas as pd

years = ["2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010",
         "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020"]

sales = {}

# add all existing brand to 'Brand' category
sales['Brand'] = sales_df['Maker'].drop_duplicates().to_list()

for i in range(len(years)):
    sales[years[i]] = sales_df.groupby(
        'Maker')[years[i]].sum().to_list()  # 2019 data by maker

total_brand_sum = len(sales['Brand'])

In [133]:
data = {'Total_Sales': []}

sales_df = pd.read_csv("dataset/Sales_table.csv")
sales_data_df = sales_df.drop(columns=['Maker', 'Genmodel', 'Genmodel_ID'])

    # all car brand name
car_brand_names = sales_df['Maker'].drop_duplicates().to_list()
for brand in car_brand_names:
    data[brand] = sales_data_df[sales_df['Maker']
                                    == brand].sum(axis=0).values[::-1]
    data['Total_Sales'].append((brand, sum(data[brand])))

print(data['FORD'])
data['Total_Sales'] = sorted(data['Total_Sales'], key=lambda n: n[1])[::-1][0:20]
data["Top_20_Brand"] = [t[0] for t in data['Total_Sales']]

[ 28528  52391  82486 108559 134923 174725 217008 225189 256458 237525
 233066 251763 283204 300241 311575 296259 260372 238331 225680 147165]
