In [59]:
import pandas
import numpy as np
price_df = pandas.read_csv("dataset/Price_table.csv")
sales_df = pandas.read_csv("dataset/Sales_table.csv")
trim_df = pandas.read_csv("dataset/Trim_table.csv")

car_spec = price_df.loc[price_df['Maker'] == 'Audi', ["Genmodel", "Entry_price"]]
car_spec = car_spec[car_spec['Entry_price'] != 0]
price_average = car_spec.groupby('Genmodel')['Entry_price'].mean()
price_average = price_average.to_dict()
# print(price_average)
data = {}
car_sales = sales_df.loc[sales_df['Maker'] == 'AUDI']
car_gen_model_names = car_sales['Genmodel'].drop_duplicates().to_list()
for genmodel in car_gen_model_names:
    specific_genmodel_df = car_sales[car_sales['Genmodel'] == genmodel]
    sales_columns = car_sales.columns[3:]
    sales_total = specific_genmodel_df[sales_columns].sum(axis=1).values[0]
    data[genmodel] = [0,0]
    data[genmodel][0] = sales_total
# at this stage we found the sales total (popularity) of each car gen model
new_data = {key.split()[-1]: value for key, value in data.items()}
# print(new_data)
gen_model_names = list(new_data.keys())
# print(gen_model_names)
for genmodel in gen_model_names:
    if genmodel in price_average.keys():
        new_data[genmodel][1] = price_average[genmodel]
new_data #index 0: sales (popularity), 1: price (average)

{'A1': [202383, 13907.777777777777],
 'A2': [9414, 12995.666666666666],
 'A3': [425659, 16529.82608695652],
 'A4': [303344, 20412.904761904763],
 'A5': [118713, 26090.0],
 'A6': [144504, 25614.428571428572],
 'A7': [16757, 42806.11111111111],
 'A8': [12108, 48167.28571428572],
 'ALLROAD': [1852, 0],
 'E-TRON': [6887, 0],
 'Q2': [56850, 20598.333333333332],
 'Q3': [118920, 24704.375],
 'Q5': [92065, 29624.545454545456],
 'Q7': [47373, 41353.769230769234],
 'Q8': [3380, 63745.0],
 'QUATTRO': [531, 0],
 'R8': [3423, 91007.08333333333],
 'RIO': [1693, 0],
 'RS3': [4875, 0],
 'RS4': [5242, 0],
 'RS5': [1443, 0],
 'RS6': [4298, 0],
 'RS7': [569, 0],
 'RSQ3': [1696, 0],
 'S1': [2868, 0],
 'S3': [28669, 0],
 'S4': [9301, 0],
 'S5': [10728, 0],
 'S6': [1320, 0],
 'S7': [532, 0],
 'S8': [1003, 0],
 'SQ2': [1247, 0],
 'SQ5': [11624, 0],
 'SQ7': [2802, 0],
 'TT': [85759, 23886.15],
 'TTRS': [956, 0],
 'TTS': [27721, 0]}

In [83]:
# VOLVO Sales from 2016 - 2020
# X = sales_df[['Maker', "2016", "2017", "2018", "2019", "2020"]].values
volvo_sales = sales_df.loc[sales_df['Maker'] ==
                           'VOLVO', ["2016", "2017", "2018", "2019", "2020"]]
# sales by car ID
# volvo_sales_array = volvo_sales.values

# total sales (each year)
volvo_sales_sum = volvo_sales.sum(axis=0)

# return an array (each year)
volvo_sales_sum = volvo_sales.sum(axis=0).values

volvo_sales_sum

array([42914, 42273, 47659, 53773, 44328])

In [84]:
# Ferrari Sales from 2016 - 2020
X = sales_df[['Maker', "2016", "2017", "2018", "2019", "2020"]].values
ferrari_sales = sales_df.loc[sales_df['Maker'] ==
                             'FERRARI', ["2016", "2017", "2018", "2019", "2020"]]
# sales by car ID
# volvo_sales_array = volvo_sales.values

# total sales (each year)
ferrari_sales_sum = ferrari_sales.sum(axis=0)

# return an array (each year)
ferrari_sales_sum = ferrari_sales.sum(axis=0).values

np.array(ferrari_sales_sum)

array([472, 485, 488, 550, 468])

In [85]:
# Toyota Sales from 2016 - 2020
X = sales_df[['Maker', "2016", "2017", "2018", "2019", "2020"]].values
toyota_sales = sales_df.loc[sales_df['Maker'] ==
                            'TOYOTA', ["2016", "2017", "2018", "2019", "2020"]]
# sales by car ID
# volvo_sales_array = volvo_sales.values

# total sales (each year)
toyota_sales_sum = toyota_sales.sum(axis=0)

# return an array (each year)
toyota_sales_sum = toyota_sales.sum(axis=0).values

toyota_sales_sum

array([89822, 91954, 95267, 99904, 90020])

In [86]:
import pandas as pd

years = ["2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010",
         "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020"]

sales = {}

# add all existing brand to 'Brand' category
sales['Brand'] = sales_df['Maker'].drop_duplicates().to_list()

for i in range(len(years)):
    sales[years[i]] = sales_df.groupby(
        'Maker')[years[i]].sum().to_list()  # 2019 data by maker

total_brand_sum = len(sales['Brand'])

In [133]:
data = {'Total_Sales': []}

sales_df = pd.read_csv("dataset/Sales_table.csv")
sales_data_df = sales_df.drop(columns=['Maker', 'Genmodel', 'Genmodel_ID'])

    # all car brand name
car_brand_names = sales_df['Maker'].drop_duplicates().to_list()
for brand in car_brand_names:
    data[brand] = sales_data_df[sales_df['Maker']
                                    == brand].sum(axis=0).values[::-1]
    data['Total_Sales'].append((brand, sum(data[brand])))

print(data['FORD'])
data['Total_Sales'] = sorted(data['Total_Sales'], key=lambda n: n[1])[::-1][0:20]
data["Top_20_Brand"] = [t[0] for t in data['Total_Sales']]

[ 28528  52391  82486 108559 134923 174725 217008 225189 256458 237525
 233066 251763 283204 300241 311575 296259 260372 238331 225680 147165]


In [75]:
import pandas
import numpy as np
sales_forecast_df = pandas.read_csv("prediction_analysis/Projected_Sales_data.csv")

columns = list(sales_forecast_df.columns)
df_segment0 = columns[0:3]
df_segment1 = columns[3:23]
df_segment2 = columns[23:29]
sales_df = df_segment0 + df_segment2[::-1] + df_segment1
sales_df

['Maker',
 'Genmodel',
 'Genmodel_ID',
 '2026',
 '2025',
 '2024',
 '2023',
 '2022',
 '2021',
 '2020',
 '2019',
 '2018',
 '2017',
 '2016',
 '2015',
 '2014',
 '2013',
 '2012',
 '2011',
 '2010',
 '2009',
 '2008',
 '2007',
 '2006',
 '2005',
 '2004',
 '2003',
 '2002',
 '2001']