In [22]:
import pandas
import numpy as np
price_df = pandas.read_csv("dataset/Price_table.csv")
sales_df = pandas.read_csv("dataset/Sales_table.csv")
trim_df = pandas.read_csv("dataset/Trim_table.csv")

In [21]:
# VOLVO Sales from 2016 - 2020
# X = sales_df[['Maker', "2016", "2017", "2018", "2019", "2020"]].values
volvo_sales = sales_df.loc[sales_df['Maker'] ==
                           'VOLVO', ["2016", "2017", "2018", "2019", "2020"]]
# sales by car ID
# volvo_sales_array = volvo_sales.values

# total sales (each year)
volvo_sales_sum = volvo_sales.sum(axis=0)

# return an array (each year)
volvo_sales_sum = volvo_sales.sum(axis=0).values

volvo_sales_sum

array([42914, 42273, 47659, 53773, 44328])

In [24]:
# Ferrari Sales from 2016 - 2020
X = sales_df[['Maker', "2016", "2017", "2018", "2019", "2020"]].values
ferrari_sales = sales_df.loc[sales_df['Maker'] ==
                           'FERRARI', ["2016", "2017", "2018", "2019", "2020"]]
# sales by car ID
# volvo_sales_array = volvo_sales.values

# total sales (each year)
ferrari_sales_sum = ferrari_sales.sum(axis=0)

# return an array (each year)
ferrari_sales_sum = ferrari_sales.sum(axis=0).values

np.array(ferrari_sales_sum)

array([472, 485, 488, 550, 468])

In [18]:
# Toyota Sales from 2016 - 2020
X = sales_df[['Maker', "2016", "2017", "2018", "2019", "2020"]].values
toyota_sales = sales_df.loc[sales_df['Maker'] ==
                             'TOYOTA', ["2016", "2017", "2018", "2019", "2020"]]
# sales by car ID
# volvo_sales_array = volvo_sales.values

# total sales (each year)
toyota_sales_sum = toyota_sales.sum(axis=0)

# return an array (each year)
toyota_sales_sum = toyota_sales.sum(axis=0).values

toyota_sales_sum

array([89822, 91954, 95267, 99904, 90020])